// These are SUGGESTION TEMPLATES only
// Shown when user taps "Choose from template"
// NOT pre-loaded into the app automatically

export const DESTINATION_TEMPLATES = [
  {
    name: "University",
    emoji: "🎓",
    imageType: "emoji",
    imageValue: "🎓",
    color: "#6B8FFF",
    bgLight: "#E8EEFF",
    type: "daily",
    time: "08:00",
    items: [
      { name: "Student Card", essential: true },
      { name: "Laptop", essential: true },
      { name: "Charger", essential: true },
      { name: "Water Bottle", essential: false },
      { name: "Notebook", essential: false },
    ],
  },
  {
    name: "Market",
    emoji: "🛒",
    imageType: "emoji",
    imageValue: "🛒",
    color: "#7DD4C0",
    bgLight: "#E6F7F4",
    type: "daily",
    time: "17:00",
    items: [
      { name: "Wallet", essential: true },
      { name: "Phone", essential: true },
      { name: "Shopping Bag", essential: false },
      { name: "Shopping List", essential: false },
    ],
  },
  {
    name: "Gym",
    emoji: "🏋️",
    imageType: "emoji",
    imageValue: "🏋️",
    color: "#C9B8FF",
    bgLight: "#F2EEFF",
    type: "daily",
    time: "06:30",
    items: [
      { name: "Gym Shoes", essential: true },
      { name: "Towel", essential: true },
      { name: "Water Bottle", essential: false },
      { name: "Earphones", essential: false },
    ],
  },
  {
    name: "Hiking",
    emoji: "🥾",
    imageType: "emoji",
    imageValue: "🥾",
    color: "#FFB347",
    bgLight: "#FFF6E0",
    type: "event",
    time: "06:00",
    items: [
      { name: "Water & Snacks", essential: true },
      { name: "First Aid Kit", essential: true },
      { name: "Power Bank", essential: false },
      { name: "Sunscreen", essential: false },
    ],
  },
  {
    name: "Travel",
    emoji: "✈️",
    imageType: "emoji",
    imageValue: "✈️",
    color: "#FF9BB5",
    bgLight: "#FFE8F0",
    type: "event",
    time: "05:00",
    items: [
      { name: "Passport", essential: true },
      { name: "Ticket", essential: true },
      { name: "Charger", essential: true },
      { name: "Medicines", essential: false },
      { name: "Earphones", essential: false },
    ],
  },
  {
    name: "Hospital",
    emoji: "🏥",
    imageType: "emoji",
    imageValue: "🏥",
    color: "#FFD166",
    bgLight: "#FFFBE0",
    type: "event",
    time: "09:00",
    items: [
      { name: "Medical Records", essential: true },
      { name: "Insurance Card", essential: true },
      { name: "Medicines", essential: true },
      { name: "Water Bottle", essential: false },
    ],
  },
  {
    name: "Office",
    emoji: "💼",
    imageType: "emoji",
    imageValue: "💼",
    color: "#6B8FFF",
    bgLight: "#E8EEFF",
    type: "daily",
    time: "08:30",
    items: [
      { name: "Laptop", essential: true },
      { name: "ID Card", essential: true },
      { name: "Charger", essential: false },
      { name: "Notebook", essential: false },
    ],
  },
];

export const EMOJIS = [
  "🎓",
  "🛒",
  "🥾",
  "🏋️",
  "✈️",
  "🏥",
  "💼",
  "🎮",
  "🏖️",
  "⛺",
  "🎵",
  "🐾",
  "🏫",
  "🍽️",
  "💊",
  "🎨",
  "🏊",
  "🚗",
  "🎒",
  "🏠",
  "🌍",
  "📚",
  "🎤",
  "🏕️",
];

export const CARD_COLORS = [
  { color: "#6B8FFF", bgLight: "#E8EEFF" },
  { color: "#7DD4C0", bgLight: "#E6F7F4" },
  { color: "#FFB347", bgLight: "#FFF6E0" },
  { color: "#C9B8FF", bgLight: "#F2EEFF" },
  { color: "#FF9BB5", bgLight: "#FFE8F0" },
  { color: "#FFD166", bgLight: "#FFFBE0" },
];

export const MOM_SCOLDS = [
  "Go pack it RIGHT NOW! 😤",
  "Don't you dare leave without it! 😠",
  "I didn't raise you to be forgetful! 😤",
  "Go back and get it! NOW! 👆",
  "Absolutely NOT leaving without it! 🚫",
];

export const MOM_PRAISE = [
  "Great job! Keep going! 💕",
  "That's my baby! ✅",
  "Perfect! You're doing amazing! 🌟",
  "Yay! One down! 🎉",
  "Look at you being responsible! 😊",
];
